//! Shared types for image-host providers.

use serde::{Deserialize, Serialize};
use specta::Type;

/// Bytes plus metadata handed to a provider's upload function.
///
/// `key` is pre-generated by `naming::generate_key`; providers that pick
/// their own key (imgur, sm.ms) ignore it.
#[derive(Debug, Clone)]
pub struct UploadInput {
    pub bytes: Vec<u8>,
    pub filename: String,
    pub mime: String,
    pub key: String,
}

/// Result of a successful upload.
#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct UploadResult {
    /// Public URL the user's Markdown should reference.
    pub url: String,
    /// The remote object key, when the provider chose one we control
    /// (S3 / OSS / Qiniu). `None` for hosts that pick their own URL
    /// scheme (imgur, sm.ms).
    pub remote_key: Option<String>,
}

/// All errors a provider's upload function can return. Mapped into
/// `AppError::Custom(...)` at the Tauri command boundary.
#[derive(Debug, thiserror::Error)]
pub enum HostError {
    #[error("Network error: {0}")]
    Network(String),
    #[error("Authentication rejected: {0}")]
    Auth(String),
    #[error("Quota exceeded: {0}")]
    QuotaExceeded(String),
    #[error("Bad config: {0}")]
    BadConfig(String),
    #[error("Host returned {status}: {message}")]
    HostError { status: u16, message: String },
    #[error("Unexpected response: {0}")]
    UnexpectedResponse(String),
    #[error("File too large: {actual} bytes (limit: {limit} bytes)")]
    FileTooLarge { limit: u64, actual: u64 },
}
